/**
 * @author Jade Yeom
 * @email ysw0094@gmail.com
 */
var commander = require('commander'), fs = require('fs'), path = require('path'), chalk = require('chalk'), walk = require('walk'), inquirer = require('inquirer'), xml2js = require('xml2js'), changeCase = require('change-case');
commander.arguments('<name>')
    .version('0.0.1')
    .option('-g, --generate [name]', 'component (e.g activity, fragment etc..)')
    .option('--adb-reset', 'kill server adb (required environment variable for ADB_PATH)')
    .action(function (name) {
    var selectedPackage;
    var parsedJavaContent;
    var parsedXMLContent;
    presentInitialMessage();
    if (commander.generate) {
        console.log(chalk.yellow(changeCase.pascalCase(commander.generate) + " will generated by Android CLI"));
        getApplicationPackage(function (pacakge) {
            getPackages(pacakge, function (packageList) {
                var questions = [{
                        type: 'list',
                        name: 'package',
                        message: "Choose your target package path",
                        // TODO ADD JAVA PACKAGE PARSED PATH LIST
                        choices: packageList
                    }];
                inquirer.prompt(questions).then(function (answers) {
                    generateRenderedOutFile(commander.generate, name, selectedPackage);
                });
            });
        });
    }
}).parse(process.argv);
function getApplicationPackage(callback) {
    // TODO GET REAL PATH
    var manifestContent = fs.readFileSync('./AndroidManifest.xml');
    var parser = new xml2js.Parser();
    parser.parseString(manifestContent, function (err, result) {
        callback(result.manifest.$.package);
    });
}
function getPackages(packageName, callback) {
    var packageList = [];
    var options = {
        followLinks: false
    };
    // TODO GET REAL PATH
    var walker = walk.walk("/tmp", options);
    walker.on("directories", function (root, dirStatsArray, next) {
        for (var _i = 0, dirStatsArray_1 = dirStatsArray; _i < dirStatsArray_1.length; _i++) {
            var dir = dirStatsArray_1[_i];
            packageList.push(dir.name);
        }
        next();
    });
    walker.on("end", function () {
        callback(packageList.map(function (value) { return packageName + "." + value; }));
    });
}
function renderAcFile(fileContent, pkgName, activityName) {
    return fileContent
        .replace(/{%packageName%}/gi, pkgName)
        .replace(/{%activityName%}/gi, changeCase.pascalCase(activityName))
        .replace(/{%activityNameLowerCase%}/gi, changeCase.lowerCase(activityName));
}
function generateRenderedOutFile(componentType, componentName, targetPkg) {
    var boilerplatesPath = "./boilerplates/" + componentType;
    var boilerplateNameOfJAVA = componentType + ".ac.java";
    var boilerplateNameOfXML = componentType + "_layout.ac.xml";
    var javaFileName = "" + changeCase.pascalCase(componentName) + changeCase.pascalCase(componentType) + ".java";
    var xmlFileName = changeCase.lowerCase(componentType) + "_" + changeCase.lowerCase(componentName) + ".xml";
    var javaContent = fs.readFileSync(boilerplatesPath + "/" + boilerplateNameOfJAVA, 'utf-8').toString();
    var xmlContent = fs.readFileSync(boilerplatesPath + "/" + boilerplateNameOfXML, 'utf-8').toString();
    var parsedJavaContent = renderAcFile(javaContent, targetPkg, componentName);
    var parsedXMLContent = renderAcFile(xmlContent, targetPkg, componentName);
    try {
        fs.writeFileSync(javaFileName, parsedJavaContent);
        console.log(chalk.green("Successful generate " + componentType + " " + javaFileName));
    }
    catch (err) {
        console.log(chalk.red("Failed to generate " + componentType + " " + javaFileName));
        console.log(chalk.red(err));
    }
    try {
        fs.writeFileSync("" + xmlFileName /*TODO GET REAL PATH*/, parsedXMLContent);
        console.log(chalk.green("Successful generate layout file " + xmlFileName));
    }
    catch (err) {
        console.log(chalk.red("Failed to generate layout file " + xmlFileName));
        console.log(chalk.red(err));
    }
}
function presentInitialMessage() {
    console.log(chalk.cyan("================================="));
    console.log(chalk.cyan("Welcome to Android CLI TOOL 0.0.1"));
    console.log(chalk.cyan("================================="));
}
